param(
  [Parameter(Mandatory = $true)]
  [string]$Repository,

  [Parameter(Mandatory = $true)]
  [string]$Tag,

  [Parameter(Mandatory = $true)]
  [string]$PackVersion,

  [Parameter(Mandatory = $true)]
  [string]$WorkflowRunId,

  [Parameter(Mandatory = $true)]
  [string]$TargetCommit,

  [Parameter(Mandatory = $true)]
  [string]$OutputPath
)

$ErrorActionPreference = "Stop"

function Invoke-GhJson {
  param(
    [Parameter(Mandatory = $true)]
    [string[]]$Arguments
  )

  $output = & gh @Arguments
  if ($LASTEXITCODE -ne 0) {
    throw "gh $($Arguments -join ' ') failed with exit code $LASTEXITCODE"
  }

  $json = ($output | Out-String).Trim()
  if ([string]::IsNullOrWhiteSpace($json)) {
    return $null
  }

  $result = $json | ConvertFrom-Json
  if ($result -is [System.Array]) {
    foreach ($item in $result) {
      $item
    }
    return
  }

  return $result
}

function Get-ChannelFromAssetName {
  param(
    [Parameter(Mandatory = $true)]
    [string]$AssetName
  )

  $lowerName = $AssetName.ToLowerInvariant()
  if ($lowerName -match "arm64") {
    return "arm64"
  }
  if ($lowerName -match "avx10-1|avx10_1") {
    return "x64-avx10-1"
  }
  if ($lowerName -match "avx512") {
    return "x64-avx512"
  }
  if ($lowerName -match "avx2") {
    return "x64-avx2"
  }

  return "unknown"
}

function Get-ChannelSortOrder {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Channel
  )

  switch ($Channel) {
    "x64-avx2" { return 10 }
    "x64-avx512" { return 20 }
    "x64-avx10-1" { return 30 }
    "arm64" { return 40 }
    default { return 100 }
  }
}

function Get-DownloadGuidance {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Channel
  )

  switch ($Channel) {
    "x64-avx2" { return "Most 64-bit Intel/AMD systems with AVX2. Use this if you are unsure which x64 build to pick." }
    "x64-avx512" { return "64-bit Intel/AMD systems where you specifically want the AVX-512 build." }
    "x64-avx10-1" { return "64-bit Intel/AMD systems with AVX10.1 support." }
    "arm64" { return "Windows on ARM64 devices." }
    default { return "Special-purpose asset. Use one of the setup executables for normal installation." }
  }
}

function Get-AssetPurpose {
  param(
    [Parameter(Mandatory = $true)]
    [string]$AssetName
  )

  $channel = Get-ChannelFromAssetName $AssetName

  if ($AssetName -match "-Setup\.exe$") {
    return "Manual installer for the $channel channel."
  }
  if ($AssetName -match "^releases\..*\.json$") {
    return "Velopack update feed for the $channel channel. UpdateChecker reads this file."
  }
  if ($AssetName -match "-full\.nupkg$") {
    return "Velopack full package for the $channel channel. Normal manual installs should use the setup executable instead."
  }
  if ($AssetName -match "-delta\.nupkg$") {
    return "Velopack delta package for the $channel channel. Update clients use it to reduce download size."
  }
  if ($AssetName -match "^EqualizerAPO-XT-source-.*\.zip$") {
    return "Source snapshot for this exact release commit."
  }

  return "Release asset generated by the build pipeline."
}

function Format-FileSize {
  param(
    [Parameter(Mandatory = $true)]
    [long]$Bytes
  )

  if ($Bytes -ge 1GB) {
    return "{0:N1} GB" -f ($Bytes / 1GB)
  }
  if ($Bytes -ge 1MB) {
    return "{0:N1} MB" -f ($Bytes / 1MB)
  }
  if ($Bytes -ge 1KB) {
    return "{0:N1} KB" -f ($Bytes / 1KB)
  }

  return "$Bytes bytes"
}

function Escape-MarkdownCell {
  param(
    [AllowNull()]
    [string]$Text
  )

  if ($null -eq $Text) {
    return ""
  }

  return $Text.Replace("|", "\|").Replace("`r", " ").Replace("`n", " ")
}

function Escape-MarkdownText {
  param(
    [AllowNull()]
    [string]$Text
  )

  if ($null -eq $Text) {
    return ""
  }

  return $Text.Replace("[", "\[").Replace("]", "\]").Replace("`r", " ").Replace("`n", " ")
}

$release = Invoke-GhJson -Arguments @("api", "repos/$Repository/releases/tags/$Tag")
$assets = @($release.assets | Sort-Object name)
$installerAssets = @(
  $assets |
    Where-Object { $_.name -match "-Setup\.exe$" } |
    Sort-Object @{ Expression = { Get-ChannelSortOrder (Get-ChannelFromAssetName $_.name) } }, name
)
$sourceAssets = @($assets | Where-Object { $_.name -match "^EqualizerAPO-XT-source-.*\.zip$" })

if ($installerAssets.Count -eq 0) {
  throw "No setup executable assets were found for release $Tag"
}

if ($sourceAssets.Count -eq 0) {
  throw "No source zip asset was found for release $Tag"
}

$previousRelease = $null
$compare = $null

try {
  $recentReleases = @(Invoke-GhJson -Arguments @("api", "repos/$Repository/releases?per_page=20"))
  $previousRelease = $recentReleases |
    Where-Object { $_.tag_name -ne $Tag -and -not $_.draft } |
    Select-Object -First 1
} catch {
  Write-Warning "Could not read previous releases: $($_.Exception.Message)"
}

if ($previousRelease) {
  try {
    $compare = Invoke-GhJson -Arguments @("api", "repos/$Repository/compare/$($previousRelease.tag_name)...$TargetCommit")
  } catch {
    Write-Warning "Could not read compare data from $($previousRelease.tag_name) to $TargetCommit`: $($_.Exception.Message)"
  }
}

$shortCommit = if ($TargetCommit.Length -gt 7) { $TargetCommit.Substring(0, 7) } else { $TargetCommit }
$workflowUrl = "https://github.com/$Repository/actions/runs/$WorkflowRunId"
$releaseUrl = "https://github.com/$Repository/releases/tag/$Tag"

$lines = [System.Collections.Generic.List[string]]::new()
[void]$lines.Add("# EqualizerAPO-XT $PackVersion")
[void]$lines.Add("")
[void]$lines.Add("Built from [$shortCommit](https://github.com/$Repository/commit/$TargetCommit) by [GitHub Actions run $WorkflowRunId]($workflowUrl).")
[void]$lines.Add("")
[void]$lines.Add("## What to download")
[void]$lines.Add("")
[void]$lines.Add("| Download | Use this when |")
[void]$lines.Add("| --- | --- |")

foreach ($asset in $installerAssets) {
  $channel = Get-ChannelFromAssetName $asset.name
  $guidance = Get-DownloadGuidance $channel
  $name = Escape-MarkdownCell $asset.name
  [void]$lines.Add("| [$name]($($asset.browser_download_url)) | $(Escape-MarkdownCell $guidance) |")
}

[void]$lines.Add("")
[void]$lines.Add('The setup executables are the normal installer downloads. The `.nupkg` and `releases.*.json` files are for the Velopack/update pipeline.')
[void]$lines.Add("")
[void]$lines.Add("## All files")
[void]$lines.Add("")
[void]$lines.Add("| File | Size | Purpose |")
[void]$lines.Add("| --- | ---: | --- |")

foreach ($asset in $assets) {
  $name = Escape-MarkdownCell $asset.name
  $size = Format-FileSize ([long]$asset.size)
  $purpose = Escape-MarkdownCell (Get-AssetPurpose $asset.name)
  [void]$lines.Add("| [$name]($($asset.browser_download_url)) | $size | $purpose |")
}

[void]$lines.Add("")
[void]$lines.Add("## Changes")
[void]$lines.Add("")

if ($previousRelease -and $compare) {
  $previousTag = Escape-MarkdownText $previousRelease.tag_name
  $previousUrl = $previousRelease.html_url
  $compareUrl = if ($compare.html_url) { $compare.html_url } else { "https://github.com/$Repository/compare/$($previousRelease.tag_name)...$Tag" }
  [void]$lines.Add("Changes since [$previousTag]($previousUrl): [$($previousRelease.tag_name)...$Tag]($compareUrl)")
  [void]$lines.Add("")

  $commits = @($compare.commits)
  if ($commits.Count -eq 0) {
    [void]$lines.Add("- No commits were reported by the GitHub compare API.")
  } else {
    $maxCommits = 30
    $listedCommits = @($commits | Select-Object -Last $maxCommits)
    foreach ($commit in $listedCommits) {
      $commitSha = [string]$commit.sha
      $commitShort = if ($commitSha.Length -gt 7) { $commitSha.Substring(0, 7) } else { $commitSha }
      $message = Escape-MarkdownText (([string]$commit.commit.message -split "`n")[0])
      [void]$lines.Add("- [$commitShort]($($commit.html_url)) $message")
    }

    if ($commits.Count -gt $maxCommits) {
      $remaining = $commits.Count - $maxCommits
      [void]$lines.Add("- ...and $remaining more commit(s). Use the compare link above for the full list.")
    }
  }
} elseif ($previousRelease) {
  [void]$lines.Add("Previous release: [$($previousRelease.tag_name)]($($previousRelease.html_url)).")
  [void]$lines.Add("")
  [void]$lines.Add("The GitHub compare API was not available while generating these notes. Read the current commit here: [${shortCommit}](https://github.com/$Repository/commit/$TargetCommit).")
} else {
  [void]$lines.Add("No previous GitHub Release was found. Read the current commit here: [${shortCommit}](https://github.com/$Repository/commit/$TargetCommit).")
}

[void]$lines.Add("")
[void]$lines.Add("## Verification")
[void]$lines.Add("")
[void]$lines.Add("The linked workflow builds x64 AVX2, x64 AVX-512, x64 AVX10.1, and ARM64 installers. It runs EditorLogicTests on every build variant and runs HybridConvTests where the GitHub-hosted runner can execute the target instruction set.")
[void]$lines.Add("")
[void]$lines.Add("Release page: [$Tag]($releaseUrl)")

$outputDirectory = Split-Path -Path $OutputPath -Parent
if (-not [string]::IsNullOrWhiteSpace($outputDirectory)) {
  New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
}

Set-Content -Path $OutputPath -Encoding UTF8 -Value $lines
Write-Host "Wrote release notes to $OutputPath"
